Repository ag278/iiec, pull requests merged in 2020-10, with the labels that each got.

#1 Update README.md
  README.md
Labels: hacktoberfest2020

#2 Update README.md
  README.md
Labels: hacktoberfest-accepted

#3 Update README
  README.md
Labels: hacktoberfest-accepted, hacktoberfest2020

#4 improve in content
  README.md
Labels: hacktoberfest-accepted, hacktoberfest2020
